### ISSUE TITLE
Need support/unable to use js executor

### ISSUE THREAD

**Issue by ravisah0242** [harshitkrverma/AutomationSuite#3]
public static void clickOnElementSvg(WebElement webElement) {

        ((JavascriptExecutor) driver).executeScript("arguments[0].click()", webElement);
        WaitHelper.waitForElementToBeDisplayed(webElement);
        WaitHelper.waitForElementToBeClickable(webElement);
        scrollToElement(webElement);
        webElement.click();
    }
    public static void sendKeysToElementSvg(WebElement webElement, WebDriver driver, String keys) {

        ((JavascriptExecutor) driver).executeScript("arguments[0].value=('.')", keys);
        WaitHelper.waitForElementToBeDisplayed(webElement);
        scrollToElement(webElement);
        webElement.sendKeys(keys);
    }
    
    I am using this code for jsexecutor, but i am getting the error 
Cannot invoke "org.openqa.selenium.JavascriptExecutor.executeScript(String, Object[])" because "mail.harshitkumarvermaAtgmail.com.utils.ElementHelper.driver" is null

**Comment by harshitkrverma** [comment]
I think you are trying to click o n web element via js executor which originally was not part of this framework.
Likely issue is with instantiation driver in class from where sendKeysToElementSvg method is called. You can  use singleton method getWebDriverWait() implanted in class SeleniumHelper to get the valid instance of web driver.
Also, I have implemented a simpler method clickViaJsExecutor() in elementHelper class, You can use this. Let me know if you face any challenge in using that method.
